name: DS course CI

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

jobs:
  Task-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Grab student changes
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Run maelstrom simulation
        if: startsWith(github.event.pull_request.head.ref, 'task')
        run: BRANCH=$(git rev-parse --abbrev-ref HEAD)
          TASK=$(echo "$BRANCH" | cut -d'/' -f2)
          PROG_LANG=$(echo "$BRANCH" | cut -d'/' -f3)
          PROFILE=$(echo "$BRANCH" | cut -d'/' -f4)
          make sim
